image: python:3.6

stages:
  - test

cache:
  paths: web/node_modules/

test_api:
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m unittest discover -p "*tests.py"

test_web:
  stage: test
  image: node:8
  script:
    - cd web
    - yarn
    - yarn test
