language: python
python:
  - 3.5
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - cd web
  - npm install
  - npm install --only=dev
script:
  - coverage run --omit=tests/*,*site-packages/*  -m unittest discover -p "*tests.py"
  - cd web
  - npm test
after_success: coveralls
