language: python
python:
  - 3.6
sudo: required
services:
  - docker

stages:
  - test

before_script: chmod +x go

jobs:
  include:
    - stage: test
      cache: pip
      script: ./go test-api
      after_success: coveralls
    - stage: test
      language: node_js
      node_js: node
      cache: yarn
      script: ./go test-web
      after_success: cd web && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
