language: python
python:
  - 3.5
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - cd web && npm install && cd ../
  - gem install coveralls-lcov
script:
  - coverage run --omit=tests/*,*site-packages/*  -m unittest discover -p "*tests.py"
  - cd web && npm test -- --coverage && cd ../
after_success:
  - coveralls-lcov -v -n web/coverage/lcov.info > coverage.json
  - coveralls --merge=coverage.json
  - eval "$(ssh-agent -s)"
#  - echo "$DEPLOY_KEY" > deploy_key.pem
#  - chmod 600 deploy_key.pem
#  - ssh-add deploy_key.pem
#  - git remote add deploy $REPO_URI
#  - git push deploy master
